const data = [
  { options: ["Introduction to Elon Musk."], start_time: 0.06 },
  {
    options: [
      "Discussion on consciousness and science.",
      "Neuralink research and impact.",
      "Neuralink enables AI connection merge.",
      '"Plasticity in human and machines."',
      "Neuralink and limbic system.",
      "Machine learning and brain communication.",
      "Neuralink's Material Science Challenges.",
      "Engineering challenges of Neuralink.",
      "Tesla's Smart Summon is discussed.",
      "Discussion on AI concerns.",
      "Introduction to Neuralink and AI.",
      "Brain sensors and neuron triggering.",
      "Brain controls impulses and behavior.",
      "Possible coexistence of digital intelligence.",
      "Regulating agencies slow and reactive.",
      "Consciousness, AI, and Simulation",
      "Neuralink's exciting future.",
      "Options for avoiding AI danger.",
      "Neuroplasticity in Human Brain.",
      "Regulation needed for AI safety.",
      "Understanding brain through Neuralink.",
      "Brain interfaces redefined.",
      "Discussion on AI consciousness.",
      "Neuralink and brain functionality.",
      "Discussion on AI and Neuralink.",
      '"Understanding consciousness through science"',
      "Brain-machine plasticity discussed.",
      "Neuralink can solve brain diseases.",
      "Revolutionizing neurosurgery with technology.",
    ],
    start_time: 54.149,
  },
  {
    options: [
      "Autonomy in stop-and-go traffic.",
      "Autonomous driving technology progress.",
      "Autonomous car messages.",
      "Tesla's accurate vector representation.",
      "Developing autopilot for transportation.",
      "Discussion on Tesla's autonomy.",
      "Tesla's progress on autonomy.",
    ],
    start_time: 1536.27,
  },
  { options: ["Importance of global civilization."], start_time: 1874.549 },
  { options: ['Carl Sagan\'s "Pale Blue Dot".'], start_time: 1926.929 },
  { options: ["The fragility of life."], start_time: 1982.82 },
  {
    options: [
      "Elon Musk talks about Earth.",
      "Discussion on Earth's existence.",
    ],
    start_time: 2041.23,
  },
];

export default data;
